# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Health_Dashboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Health_Dashboard
  pod 'ResearchKit', '~> 1.0'
  pod 'CareKit', '~> 1.2'

  target 'Health_DashboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Health_DashboardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
