# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ResearchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ResearchKit App
  pod 'ResearchKit', '~> 1.0'

  target 'ResearchKit AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ResearchKit AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
